// Monthly Travelcard prices (28-day, Adult, 2026 rates)
const MONTHLY_TRAVELCARD_PRICES = {
  '1': 171.70,
  '1-2': 171.70,
  '1-3': 201.60,
  '1-4': 246.60,
  '1-5': 293.40,
  '1-6': 313.40,
  '1-7': 341.40,
  '1-8': 402.90,
  '1-9': 447.00,
  '2': 128.70,
  '2-3': 128.70,
  '2-4': 142.50,
  '2-5': 170.90,
  '2-6': 214.70,
  '3': 128.70,
  '3-4': 128.70,
  '3-5': 142.50,
  '3-6': 170.90,
  '4': 128.70,
  '4-5': 128.70,
  '4-6': 142.50,
  '5': 128.70,
  '5-6': 128.70,
  '6': 128.70
};

// Daily caps for different zone combinations (2026 rates)
const DAILY_CAPS = {
  'bus': 5.25,
  '1': 8.90,
  '1-2': 8.90,
  '1-3': 10.50,
  '1-4': 12.80,
  '1-5': 15.30,
  '1-6': 16.30,
  '1-7': 17.80,
  '1-8': 21.00,
  '1-9': 23.30,
  '2': 8.90,
  '2-3': 10.50,
  '2-4': 12.80,
  '2-5': 15.30,
  '2-6': 16.30
};

// TFL Station Data
const STATION_ZONES = {
  "Bank": [1],
  "Oxford Circus": [1],
  "King's Cross St. Pancras": [1],
  "Liverpool Street": [1],
  "Paddington": [1],
  "Victoria": [1],
  "Waterloo": [1],
  "Green Park": [1],
  "Leicester Square": [1],
  "Tottenham Court Road": [1],
  "Bond Street": [1],
  "Baker Street": [1],
  "Euston": [1],
  "Westminster": [1],
  "Embankment": [1],
  "Piccadilly Circus": [1],
  "Charing Cross": [1],
  "Holborn": [1],
  "Covent Garden": [1],
  "Russell Square": [1],
  "Goodge Street": [1],
  "Warren Street": [1],
  "St. Paul's": [1],
  "Chancery Lane": [1],
  "Temple": [1],
  "Blackfriars": [1],
  "Mansion House": [1],
  "Cannon Street": [1],
  "Monument": [1],
  "Tower Hill": [1],
  "Aldgate": [1],
  "Moorgate": [1],
  "Barbican": [1],
  "Farringdon": [1],
  "Old Street": [1],
  "Angel": [1],
  "Euston Square": [1],
  "Great Portland Street": [1],
  "Regent's Park": [1],
  "Edgware Road (Bakerloo)": [1],
  "Edgware Road (Circle)": [1],
  "Marylebone": [1],
  "Sloane Square": [1],
  "St. James's Park": [1],
  "Hyde Park Corner": [1],
  "Knightsbridge": [1],
  "South Kensington": [1],
  "Gloucester Road": [1],
  "High Street Kensington": [1],
  "Notting Hill Gate": [1],
  "Bayswater": [1],
  "Lancaster Gate": [1],
  "Marble Arch": [1],
  "Queensway": [1],
  "Royal Oak": [1],
  "Westbourne Park": [1],
  "Ladbroke Grove": [1],
  "Latimer Road": [1],
  "Lambeth North": [1],
  "Southwark": [1],
  "Borough": [1],
  "London Bridge": [1],
  "Bermondsey": [1],
  "Tower Gateway": [1],
  "Vauxhall": [1, 2],
  "Pimlico": [1, 2],
  "Elephant & Castle": [1, 2],
  "Kennington": [1, 2],
  "Oval": [1, 2],
  "Bethnal Green": [2],
  "Whitechapel": [2],
  "Shadwell": [2],
  "Wapping": [2],
  "Rotherhithe": [2],
  "Canada Water": [2],
  "Surrey Quays": [2],
  "Stockwell": [2],
  "Clapham North": [2],
  "Clapham Common": [2],
  "Clapham South": [2],
  "Balham": [2],
  "Mile End": [2],
  "Bow Road": [2],
  "Stepney Green": [2],
  "Shoreditch High Street": [2],
  "Hoxton": [2],
  "Haggerston": [2],
  "Dalston Junction": [2],
  "Dalston Kingsland": [2],
  "Canonbury": [2],
  "Highbury & Islington": [2],
  "Caledonian Road": [2],
  "Holloway Road": [2],
  "Arsenal": [2],
  "Finsbury Park": [2],
  "Manor House": [2],
  "Camden Town": [2],
  "Chalk Farm": [2],
  "Kentish Town": [2],
  "Tufnell Park": [2],
  "Mornington Crescent": [2],
  "Kilburn Park": [2],
  "Maida Vale": [2],
  "Warwick Avenue": [2],
  "St. John's Wood": [2],
  "Swiss Cottage": [2],
  "West Hampstead": [2, 3],
  "Finchley Road": [2],
  "Kilburn": [2],
  "West Brompton": [2],
  "Earl's Court": [1, 2],
  "Barons Court": [2],
  "Hammersmith": [2],
  "Goldhawk Road": [2],
  "Shepherd's Bush Market": [2],
  "Shepherd's Bush (Central)": [2],
  "White City": [2],
  "Wood Lane": [2],
  "East Acton": [2],
  "North Acton": [2],
  "West Acton": [3],
  "Ealing Common": [3],
  "Acton Town": [3],
  "Turnham Green": [2, 3],
  "Stamford Brook": [2],
  "Ravenscourt Park": [2],
  "Gunnersbury": [3],
  "Kew Gardens": [3, 4],
  "Richmond": [4],
  "Putney Bridge": [2],
  "Parsons Green": [2],
  "Fulham Broadway": [2],
  "West Kensington": [2],
  "Aldgate East": [2],
  "Limehouse": [2],
  "Westferry": [2],
  "Poplar": [2],
  "Blackwall": [2],
  "East India": [2, 3],
  "Canary Wharf": [2],
  "Heron Quays": [2],
  "South Quay": [2],
  "Crossharbour": [2],
  "Mudchute": [2],
  "Island Gardens": [2],
  "Cutty Sark": [2, 3],
  "Greenwich": [2, 3],
  "Deptford Bridge": [2],
  "Elverson Road": [2, 3],
  "Lewisham": [2, 3],
  "Canning Town": [2, 3],
  "Royal Victoria": [3],
  "Custom House": [3],
  "Prince Regent": [3],
  "Royal Albert": [3],
  "Beckton Park": [3],
  "Cyprus": [3],
  "Gallions Reach": [3],
  "Beckton": [3],
  "Stratford": [2, 3],
  "Stratford High Street": [2, 3],
  "Abbey Road": [3],
  "West Ham": [2, 3],
  "Plaistow": [2, 3],
  "Upton Park": [2, 3],
  "East Ham": [2, 3],
  "Barking": [4],
  "Bromley-by-Bow": [2, 3],
  "Tooting Bec": [3],
  "Tooting Broadway": [3],
  "Colliers Wood": [3],
  "South Wimbledon": [3],
  "Morden": [4],
  "Belsize Park": [2],
  "Hampstead": [2, 3],
  "Golders Green": [3],
  "Brent Cross": [3],
  "Hendon Central": [3, 4],
  "Colindale": [4],
  "Burnt Oak": [4],
  "Edgware": [5],
  "Archway": [2, 3],
  "Highgate": [3],
  "East Finchley": [3],
  "Finchley Central": [4],
  "West Finchley": [4],
  "Woodside Park": [4],
  "Totteridge & Whetstone": [4],
  "High Barnet": [5],
  "Mill Hill East": [4],
  "Leyton": [3],
  "Leytonstone": [3, 4],
  "Wanstead": [4],
  "Redbridge": [4],
  "Gants Hill": [4],
  "Newbury Park": [4],
  "Barkingside": [4],
  "Fairlop": [4],
  "Hainault": [4],
  "Grange Hill": [4],
  "Chigwell": [4],
  "Roding Valley": [4],
  "Snaresbrook": [4],
  "South Woodford": [4],
  "Woodford": [4],
  "Buckhurst Hill": [5],
  "Loughton": [6],
  "Debden": [6],
  "Theydon Bois": [6],
  "Epping": [6],
  "Turnpike Lane": [3],
  "Wood Green": [3],
  "Bounds Green": [3, 4],
  "Arnos Grove": [4],
  "Southgate": [4],
  "Oakwood": [5],
  "Cockfosters": [5],
  "Seven Sisters": [3],
  "Tottenham Hale": [3],
  "Blackhorse Road": [3],
  "Walthamstow Central": [3],
  "Brixton": [2],
  "Battersea Power Station": [1, 2],
  "Nine Elms": [1, 2],
  "Alperton": [4],
  "Park Royal": [3],
  "North Ealing": [3],
  "Ealing Broadway": [3],
  "Perivale": [4],
  "Hanger Lane": [3],
  "Greenford": [4],
  "Northolt": [5],
  "South Ruislip": [5],
  "Ruislip Gardens": [5],
  "West Ruislip": [6],
  "Hounslow East": [4],
  "Hounslow Central": [4],
  "Hounslow West": [5],
  "Hatton Cross": [5, 6],
  "Heathrow Terminals 2 & 3": [6],
  "Heathrow Terminal 4": [6],
  "Heathrow Terminal 5": [6],
  "Osterley": [4],
  "Boston Manor": [4],
  "Northfields": [3],
  "South Ealing": [3],
  "Acton Central": [3],
  "South Acton": [2, 3],
  "Chiswick Park": [3],
  "Wimbledon": [3],
  "Wimbledon Park": [3],
  "Southfields": [3],
  "East Putney": [2, 3],
  "Upney": [4],
  "Becontree": [5],
  "Dagenham Heathway": [5],
  "Dagenham East": [5],
  "Elm Park": [6],
  "Hornchurch": [6],
  "Upminster Bridge": [6],
  "Upminster": [6],
  "Harrow-on-the-Hill": [5],
  "North Harrow": [5],
  "Pinner": [5],
  "Northwood Hills": [6],
  "Northwood": [6],
  "Moor Park": [6, 7],
  "Rickmansworth": [7],
  "Chorleywood": [7],
  "Chalfont & Latimer": [7, 8],
  "Amersham": [9],
  "Chesham": [9],
  "Watford": [7],
  "Croxley": [7],
  "Wembley Park": [4],
  "Neasden": [3],
  "Dollis Hill": [3],
  "Willesden Green": [2, 3],
  "North Greenwich": [2, 3],
  "Woolwich": [4],
  "Abbey Wood": [4],
  "Woolwich Arsenal": [4],
  
  // Tram stop zones
  "Addiscombe": [4],
  "Addington Village": [5],
  "Ampere Way": [4],
  "Arena": [4],
  "Avenue Road": [4],
  "Beckenham Junction": [4],
  "Beckenham Road": [4],
  "Beddington Lane": [5],
  "Belgrave Walk": [4],
  "Birkbeck": [4],
  "Blackhorse Lane": [3],
  "Centrale": [5],
  "Church Street": [4],
  "Coombe Lane": [4],
  "Dundonald Road": [4],
  "East Croydon": [5],
  "Elmers End": [4],
  "Fieldway": [5],
  "George Street": [4],
  "Gravel Hill": [4],
  "Harrington Road": [4],
  "King Henry's Drive": [4],
  "Lebanon Road": [4],
  "Lloyd Park": [4],
  "Merton Park": [3],
  "Mitcham": [4],
  "Mitcham Junction": [4],
  "Morden Road": [4],
  "New Addington": [6],
  "Phipps Bridge": [4],
  "Reeves Corner": [5],
  "Sandilands": [5],
  "Therapia Lane": [5],
  "Waddon Marsh": [5],
  "Wandle Park": [4],
  "Wellesley Road": [5],
  "West Croydon": [5],
  "Woodside": [4]
};

const TFL_STATIONS = [
  {"name": "Aldgate", "lines": ["circle", "metropolitan"]},
  {"name": "Aldgate East", "lines": ["district", "hammersmith"]},
  {"name": "Alperton", "lines": ["piccadilly"]},
  {"name": "Amersham", "lines": ["metropolitan"]},
  {"name": "Angel", "lines": ["northern"]},
  {"name": "Archway", "lines": ["northern"]},
  {"name": "Arnos Grove", "lines": ["piccadilly"]},
  {"name": "Arsenal", "lines": ["piccadilly"]},
  {"name": "Baker Street", "lines": ["bakerloo", "circle", "hammersmith", "metropolitan", "jubilee"]},
  {"name": "Balham", "lines": ["northern"]},
  {"name": "Bank", "lines": ["central", "northern", "waterloo", "dlr"]},
  {"name": "Barbican", "lines": ["circle", "hammersmith", "metropolitan"]},
  {"name": "Barking", "lines": ["district", "hammersmith", "overground"]},
  {"name": "Barkingside", "lines": ["central"]},
  {"name": "Barons Court", "lines": ["district", "piccadilly"]},
  {"name": "Battersea Power Station", "lines": ["northern"]},
  {"name": "Bayswater", "lines": ["circle", "district"]},
  {"name": "Becontree", "lines": ["district"]},
  {"name": "Belsize Park", "lines": ["northern"]},
  {"name": "Bermondsey", "lines": ["jubilee"]},
  {"name": "Bethnal Green", "lines": ["central"]},
  {"name": "Blackfriars", "lines": ["circle", "district"]},
  {"name": "Blackhorse Road", "lines": ["victoria", "overground"]},
  {"name": "Blackwall", "lines": ["dlr"]},
  {"name": "Bond Street", "lines": ["central", "jubilee", "elizabeth"]},
  {"name": "Borough", "lines": ["northern"]},
  {"name": "Boston Manor", "lines": ["piccadilly"]},
  {"name": "Bounds Green", "lines": ["piccadilly"]},
  {"name": "Bow Road", "lines": ["district", "hammersmith"]},
  {"name": "Brent Cross", "lines": ["northern"]},
  {"name": "Brixton", "lines": ["victoria"]},
  {"name": "Bromley-by-Bow", "lines": ["district", "hammersmith"]},
  {"name": "Buckhurst Hill", "lines": ["central"]},
  {"name": "Burnt Oak", "lines": ["northern"]},
  {"name": "Caledonian Road", "lines": ["piccadilly"]},
  {"name": "Camden Town", "lines": ["northern"]},
  {"name": "Canada Water", "lines": ["jubilee", "overground"]},
  {"name": "Canary Wharf", "lines": ["jubilee", "elizabeth", "dlr"]},
  {"name": "Canning Town", "lines": ["jubilee", "elizabeth", "dlr"]},
  {"name": "Cannon Street", "lines": ["circle", "district"]},
  {"name": "Canonbury", "lines": ["overground"]},
  {"name": "Canons Park", "lines": ["jubilee"]},
  {"name": "Chalfont & Latimer", "lines": ["metropolitan"]},
  {"name": "Chalk Farm", "lines": ["northern"]},
  {"name": "Chancery Lane", "lines": ["central"]},
  {"name": "Charing Cross", "lines": ["bakerloo", "northern"]},
  {"name": "Chesham", "lines": ["metropolitan"]},
  {"name": "Chigwell", "lines": ["central"]},
  {"name": "Chiswick Park", "lines": ["district"]},
  {"name": "Chorleywood", "lines": ["metropolitan"]},
  {"name": "Clapham Common", "lines": ["northern"]},
  {"name": "Clapham North", "lines": ["northern"]},
  {"name": "Clapham South", "lines": ["northern"]},
  {"name": "Cockfosters", "lines": ["piccadilly"]},
  {"name": "Colindale", "lines": ["northern"]},
  {"name": "Colliers Wood", "lines": ["northern"]},
  {"name": "Covent Garden", "lines": ["piccadilly"]},
  {"name": "Crossharbour", "lines": ["dlr"]},
  {"name": "Croxley", "lines": ["metropolitan"]},
  {"name": "Custom House", "lines": ["elizabeth", "dlr"]},
  {"name": "Cutty Sark", "lines": ["dlr"]},
  {"name": "Dagenham East", "lines": ["district"]},
  {"name": "Dagenham Heathway", "lines": ["district"]},
  {"name": "Dalston Junction", "lines": ["overground"]},
  {"name": "Dalston Kingsland", "lines": ["overground"]},
  {"name": "Debden", "lines": ["central"]},
  {"name": "Dollis Hill", "lines": ["jubilee"]},
  {"name": "Ealing Broadway", "lines": ["central", "district", "elizabeth"]},
  {"name": "Ealing Common", "lines": ["district", "piccadilly"]},
  {"name": "Earl's Court", "lines": ["district", "piccadilly"]},
  {"name": "East Acton", "lines": ["central"]},
  {"name": "East Finchley", "lines": ["northern"]},
  {"name": "East Ham", "lines": ["district", "hammersmith"]},
  {"name": "East India", "lines": ["dlr"]},
  {"name": "East Putney", "lines": ["district"]},
  {"name": "Eastcote", "lines": ["metropolitan", "piccadilly"]},
  {"name": "Edgware", "lines": ["northern"]},
  {"name": "Edgware Road (Bakerloo)", "lines": ["bakerloo"]},
  {"name": "Edgware Road (Circle)", "lines": ["circle", "district", "hammersmith"]},
  {"name": "Elephant & Castle", "lines": ["bakerloo", "northern"]},
  {"name": "Elm Park", "lines": ["district"]},
  {"name": "Embankment", "lines": ["bakerloo", "northern", "circle", "district"]},
  {"name": "Epping", "lines": ["central"]},
  {"name": "Euston", "lines": ["northern", "victoria"]},
  {"name": "Euston Square", "lines": ["circle", "hammersmith", "metropolitan"]},
  {"name": "Fairlop", "lines": ["central"]},
  {"name": "Farringdon", "lines": ["circle", "hammersmith", "metropolitan", "elizabeth"]},
  {"name": "Finchley Central", "lines": ["northern"]},
  {"name": "Finchley Road", "lines": ["jubilee", "metropolitan"]},
  {"name": "Finsbury Park", "lines": ["piccadilly", "victoria"]},
  {"name": "Fulham Broadway", "lines": ["district"]},
  {"name": "Gants Hill", "lines": ["central"]},
  {"name": "Gloucester Road", "lines": ["circle", "district", "piccadilly"]},
  {"name": "Golders Green", "lines": ["northern"]},
  {"name": "Goldhawk Road", "lines": ["hammersmith"]},
  {"name": "Goodge Street", "lines": ["northern"]},
  {"name": "Grange Hill", "lines": ["central"]},
  {"name": "Great Portland Street", "lines": ["circle", "hammersmith", "metropolitan"]},
  {"name": "Green Park", "lines": ["jubilee", "piccadilly", "victoria"]},
  {"name": "Greenford", "lines": ["central"]},
  {"name": "Greenwich", "lines": ["dlr"]},
  {"name": "Gunnersbury", "lines": ["district", "overground"]},
  {"name": "Haggerston", "lines": ["overground"]},
  {"name": "Hainault", "lines": ["central"]},
  {"name": "Hammersmith", "lines": ["district", "hammersmith", "piccadilly"]},
  {"name": "Hampstead", "lines": ["northern"]},
  {"name": "Hanger Lane", "lines": ["central"]},
  {"name": "Harlesden", "lines": ["bakerloo", "overground"]},
  {"name": "Harrow & Wealdstone", "lines": ["bakerloo", "overground"]},
  {"name": "Harrow-on-the-Hill", "lines": ["metropolitan"]},
  {"name": "Hatton Cross", "lines": ["piccadilly"]},
  {"name": "Heathrow Terminal 4", "lines": ["piccadilly"]},
  {"name": "Heathrow Terminal 5", "lines": ["piccadilly"]},
  {"name": "Heathrow Terminals 2 & 3", "lines": ["piccadilly"]},
  {"name": "Hendon Central", "lines": ["northern"]},
  {"name": "Heron Quays", "lines": ["dlr"]},
  {"name": "High Barnet", "lines": ["northern"]},
  {"name": "High Street Kensington", "lines": ["circle", "district"]},
  {"name": "Highbury & Islington", "lines": ["victoria", "overground"]},
  {"name": "Highgate", "lines": ["northern"]},
  {"name": "Hillingdon", "lines": ["metropolitan", "piccadilly"]},
  {"name": "Holborn", "lines": ["central", "piccadilly"]},
  {"name": "Holland Park", "lines": ["central"]},
  {"name": "Holloway Road", "lines": ["piccadilly"]},
  {"name": "Hornchurch", "lines": ["district"]},
  {"name": "Hounslow Central", "lines": ["piccadilly"]},
  {"name": "Hounslow East", "lines": ["piccadilly"]},
  {"name": "Hounslow West", "lines": ["piccadilly"]},
  {"name": "Hoxton", "lines": ["overground"]},
  {"name": "Hyde Park Corner", "lines": ["piccadilly"]},
  {"name": "Ickenham", "lines": ["metropolitan", "piccadilly"]},
  {"name": "Island Gardens", "lines": ["dlr"]},
  {"name": "Kennington", "lines": ["northern"]},
  {"name": "Kensal Green", "lines": ["bakerloo", "overground"]},
  {"name": "Kensington (Olympia)", "lines": ["district", "overground"]},
  {"name": "Kentish Town", "lines": ["northern"]},
  {"name": "Kenton", "lines": ["bakerloo"]},
  {"name": "Kew Gardens", "lines": ["district", "overground"]},
  {"name": "Kilburn", "lines": ["jubilee"]},
  {"name": "Kilburn Park", "lines": ["bakerloo"]},
  {"name": "King's Cross St. Pancras", "lines": ["circle", "hammersmith", "metropolitan", "northern", "piccadilly", "victoria"]},
  {"name": "Kingsbury", "lines": ["jubilee"]},
  {"name": "Knightsbridge", "lines": ["piccadilly"]},
  {"name": "Ladbroke Grove", "lines": ["hammersmith"]},
  {"name": "Lambeth North", "lines": ["bakerloo"]},
  {"name": "Lancaster Gate", "lines": ["central"]},
  {"name": "Latimer Road", "lines": ["hammersmith"]},
  {"name": "Leicester Square", "lines": ["northern", "piccadilly"]},
  {"name": "Lewisham", "lines": ["dlr"]},
  {"name": "Leyton", "lines": ["central"]},
  {"name": "Leytonstone", "lines": ["central"]},
  {"name": "Limehouse", "lines": ["dlr"]},
  {"name": "Liverpool Street", "lines": ["central", "circle", "hammersmith", "metropolitan", "elizabeth"]},
  {"name": "London Bridge", "lines": ["jubilee", "northern"]},
  {"name": "Loughton", "lines": ["central"]},
  {"name": "Maida Vale", "lines": ["bakerloo"]},
  {"name": "Manor House", "lines": ["piccadilly"]},
  {"name": "Mansion House", "lines": ["circle", "district"]},
  {"name": "Marble Arch", "lines": ["central"]},
  {"name": "Marylebone", "lines": ["bakerloo"]},
  {"name": "Mile End", "lines": ["central", "district", "hammersmith"]},
  {"name": "Mill Hill East", "lines": ["northern"]},
  {"name": "Monument", "lines": ["circle", "district", "dlr"]},
  {"name": "Moor Park", "lines": ["metropolitan"]},
  {"name": "Moorgate", "lines": ["circle", "hammersmith", "metropolitan", "northern"]},
  {"name": "Morden", "lines": ["northern"]},
  {"name": "Mornington Crescent", "lines": ["northern"]},
  {"name": "Mudchute", "lines": ["dlr"]},
  {"name": "Neasden", "lines": ["jubilee"]},
  {"name": "Newbury Park", "lines": ["central"]},
  {"name": "Nine Elms", "lines": ["northern"]},
  {"name": "North Acton", "lines": ["central"]},
  {"name": "North Ealing", "lines": ["piccadilly"]},
  {"name": "North Greenwich", "lines": ["jubilee"]},
  {"name": "North Harrow", "lines": ["metropolitan"]},
  {"name": "North Wembley", "lines": ["bakerloo"]},
  {"name": "Northfields", "lines": ["piccadilly"]},
  {"name": "Northolt", "lines": ["central"]},
  {"name": "Northwick Park", "lines": ["metropolitan"]},
  {"name": "Northwood", "lines": ["metropolitan"]},
  {"name": "Northwood Hills", "lines": ["metropolitan"]},
  {"name": "Notting Hill Gate", "lines": ["central", "circle", "district"]},
  {"name": "Oakwood", "lines": ["piccadilly"]},
  {"name": "Old Street", "lines": ["northern"]},
  {"name": "Osterley", "lines": ["piccadilly"]},
  {"name": "Oval", "lines": ["northern"]},
  {"name": "Oxford Circus", "lines": ["bakerloo", "central", "victoria"]},
  {"name": "Paddington", "lines": ["bakerloo", "circle", "district", "hammersmith", "elizabeth"]},
  {"name": "Park Royal", "lines": ["piccadilly"]},
  {"name": "Parsons Green", "lines": ["district"]},
  {"name": "Perivale", "lines": ["central"]},
  {"name": "Piccadilly Circus", "lines": ["bakerloo", "piccadilly"]},
  {"name": "Pimlico", "lines": ["victoria"]},
  {"name": "Pinner", "lines": ["metropolitan"]},
  {"name": "Plaistow", "lines": ["district", "hammersmith"]},
  {"name": "Poplar", "lines": ["dlr"]},
  {"name": "Preston Road", "lines": ["metropolitan"]},
  {"name": "Prince Regent", "lines": ["dlr"]},
  {"name": "Putney Bridge", "lines": ["district"]},
  {"name": "Queen's Park", "lines": ["bakerloo", "overground"]},
  {"name": "Queensbury", "lines": ["jubilee"]},
  {"name": "Queensway", "lines": ["central"]},
  {"name": "Ravenscourt Park", "lines": ["district"]},
  {"name": "Rayners Lane", "lines": ["metropolitan", "piccadilly"]},
  {"name": "Redbridge", "lines": ["central"]},
  {"name": "Regent's Park", "lines": ["bakerloo"]},
  {"name": "Richmond", "lines": ["district", "overground"]},
  {"name": "Rickmansworth", "lines": ["metropolitan"]},
  {"name": "Roding Valley", "lines": ["central"]},
  {"name": "Rotherhithe", "lines": ["overground"]},
  {"name": "Royal Albert", "lines": ["dlr"]},
  {"name": "Royal Oak", "lines": ["hammersmith"]},
  {"name": "Royal Victoria", "lines": ["dlr"]},
  {"name": "Ruislip", "lines": ["metropolitan", "piccadilly"]},
  {"name": "Ruislip Gardens", "lines": ["central"]},
  {"name": "Ruislip Manor", "lines": ["metropolitan", "piccadilly"]},
  {"name": "Russell Square", "lines": ["piccadilly"]},
  {"name": "Seven Sisters", "lines": ["victoria", "overground"]},
  {"name": "Shadwell", "lines": ["overground", "dlr"]},
  {"name": "Shepherd's Bush (Central)", "lines": ["central"]},
  {"name": "Shepherd's Bush Market", "lines": ["hammersmith"]},
  {"name": "Shoreditch High Street", "lines": ["overground"]},
  {"name": "Sloane Square", "lines": ["circle", "district"]},
  {"name": "Snaresbrook", "lines": ["central"]},
  {"name": "South Acton", "lines": ["overground"]},
  {"name": "South Ealing", "lines": ["piccadilly"]},
  {"name": "South Harrow", "lines": ["piccadilly"]},
  {"name": "South Kensington", "lines": ["circle", "district", "piccadilly"]},
  {"name": "South Kenton", "lines": ["bakerloo"]},
  {"name": "South Quay", "lines": ["dlr"]},
  {"name": "South Ruislip", "lines": ["central"]},
  {"name": "South Wimbledon", "lines": ["northern"]},
  {"name": "South Woodford", "lines": ["central"]},
  {"name": "Southfields", "lines": ["district"]},
  {"name": "Southgate", "lines": ["piccadilly"]},
  {"name": "Southwark", "lines": ["jubilee"]},
  {"name": "St. James's Park", "lines": ["circle", "district"]},
  {"name": "St. John's Wood", "lines": ["jubilee"]},
  {"name": "St. Paul's", "lines": ["central"]},
  {"name": "Stamford Brook", "lines": ["district"]},
  {"name": "Stanmore", "lines": ["jubilee"]},
  {"name": "Stepney Green", "lines": ["district", "hammersmith"]},
  {"name": "Stockwell", "lines": ["northern", "victoria"]},
  {"name": "Stonebridge Park", "lines": ["bakerloo"]},
  {"name": "Stratford", "lines": ["central", "jubilee", "elizabeth", "dlr"]},
  {"name": "Stratford High Street", "lines": ["overground", "dlr"]},
  {"name": "Sudbury Hill", "lines": ["piccadilly"]},
  {"name": "Sudbury Town", "lines": ["piccadilly"]},
  {"name": "Surrey Quays", "lines": ["overground"]},
  {"name": "Swiss Cottage", "lines": ["jubilee"]},
  {"name": "Temple", "lines": ["circle", "district"]},
  {"name": "Theydon Bois", "lines": ["central"]},
  {"name": "Tooting Bec", "lines": ["northern"]},
  {"name": "Tooting Broadway", "lines": ["northern"]},
  {"name": "Tottenham Court Road", "lines": ["central", "northern", "elizabeth"]},
  {"name": "Tottenham Hale", "lines": ["victoria", "overground"]},
  {"name": "Totteridge & Whetstone", "lines": ["northern"]},
  {"name": "Tower Gateway", "lines": ["dlr"]},
  {"name": "Tower Hill", "lines": ["circle", "district"]},
  {"name": "Tufnell Park", "lines": ["northern"]},
  {"name": "Turnham Green", "lines": ["district", "piccadilly"]},
  {"name": "Turnpike Lane", "lines": ["piccadilly"]},
  {"name": "Upminster", "lines": ["district"]},
  {"name": "Upminster Bridge", "lines": ["district"]},
  {"name": "Upney", "lines": ["district"]},
  {"name": "Upton Park", "lines": ["district", "hammersmith"]},
  {"name": "Uxbridge", "lines": ["metropolitan", "piccadilly"]},
  {"name": "Vauxhall", "lines": ["victoria"]},
  {"name": "Victoria", "lines": ["circle", "district", "victoria"]},
  {"name": "Walthamstow Central", "lines": ["victoria", "overground"]},
  {"name": "Wanstead", "lines": ["central"]},
  {"name": "Wapping", "lines": ["overground"]},
  {"name": "Warren Street", "lines": ["northern", "victoria"]},
  {"name": "Warwick Avenue", "lines": ["bakerloo"]},
  {"name": "Waterloo", "lines": ["bakerloo", "northern", "jubilee", "waterloo"]},
  {"name": "Watford", "lines": ["metropolitan"]},
  {"name": "Wembley Central", "lines": ["bakerloo", "overground"]},
  {"name": "Wembley Park", "lines": ["jubilee", "metropolitan"]},
  {"name": "West Acton", "lines": ["central"]},
  {"name": "West Brompton", "lines": ["district", "overground"]},
  {"name": "West Finchley", "lines": ["northern"]},
  {"name": "West Ham", "lines": ["district", "hammersmith", "jubilee", "elizabeth"]},
  {"name": "West Hampstead", "lines": ["jubilee", "overground"]},
  {"name": "West Kensington", "lines": ["district"]},
  {"name": "West Ruislip", "lines": ["central"]},
  {"name": "Westbourne Park", "lines": ["hammersmith"]},
  {"name": "Westferry", "lines": ["dlr"]},
  {"name": "Westminster", "lines": ["circle", "district", "jubilee"]},
  {"name": "White City", "lines": ["central"]},
  {"name": "Whitechapel", "lines": ["district", "hammersmith", "elizabeth", "overground"]},
  {"name": "Willesden Green", "lines": ["jubilee"]},
  {"name": "Willesden Junction", "lines": ["bakerloo", "overground"]},
  {"name": "Wimbledon", "lines": ["district", "tram"]},
  {"name": "Wimbledon Park", "lines": ["district"]},
  {"name": "Wood Green", "lines": ["piccadilly"]},
  {"name": "Wood Lane", "lines": ["hammersmith"]},
  {"name": "Woodford", "lines": ["central"]},
  {"name": "Woodside Park", "lines": ["northern"]},
  {"name": "Woolwich", "lines": ["elizabeth", "dlr"]},
  {"name": "Woolwich Arsenal", "lines": ["dlr"]},
  {"name": "Abbey Wood", "lines": ["elizabeth"]},
  {"name": "Acton Main Line", "lines": ["elizabeth"]},
  {"name": "Brentwood", "lines": ["elizabeth"]},
  {"name": "Burnham", "lines": ["elizabeth"]},
  {"name": "Chadwell Heath", "lines": ["elizabeth"]},
  {"name": "Forest Gate", "lines": ["elizabeth"]},
  {"name": "Gidea Park", "lines": ["elizabeth"]},
  {"name": "Goodmayes", "lines": ["elizabeth"]},
  {"name": "Hanwell", "lines": ["elizabeth"]},
  {"name": "Harold Wood", "lines": ["elizabeth"]},
  {"name": "Hayes & Harlington", "lines": ["elizabeth"]},
  {"name": "Ilford", "lines": ["elizabeth"]},
  {"name": "Iver", "lines": ["elizabeth"]},
  {"name": "Langley", "lines": ["elizabeth"]},
  {"name": "Maidenhead", "lines": ["elizabeth"]},
  {"name": "Manor Park", "lines": ["elizabeth"]},
  {"name": "Maryland", "lines": ["elizabeth"]},
  {"name": "Reading", "lines": ["elizabeth"]},
  {"name": "Romford", "lines": ["elizabeth"]},
  {"name": "Seven Kings", "lines": ["elizabeth"]},
  {"name": "Shenfield", "lines": ["elizabeth"]},
  {"name": "Slough", "lines": ["elizabeth"]},
  {"name": "Southall", "lines": ["elizabeth"]},
  {"name": "Taplow", "lines": ["elizabeth"]},
  {"name": "Twyford", "lines": ["elizabeth"]},
  {"name": "West Drayton", "lines": ["elizabeth"]},
  {"name": "West Ealing", "lines": ["elizabeth"]},
  {"name": "Acton Central", "lines": ["overground"]},
  {"name": "Anerley", "lines": ["overground"]},
  {"name": "Brockley", "lines": ["overground"]},
  {"name": "Brondesbury", "lines": ["overground"]},
  {"name": "Brondesbury Park", "lines": ["overground"]},
  {"name": "Bruce Grove", "lines": ["overground"]},
  {"name": "Bush Hill Park", "lines": ["overground"]},
  {"name": "Caledonian Road & Barnsbury", "lines": ["overground"]},
  {"name": "Camden Road", "lines": ["overground"]},
  {"name": "Cheshunt", "lines": ["overground"]},
  {"name": "Clapham High Street", "lines": ["overground"]},
  {"name": "Clapham Junction", "lines": ["overground"]},
  {"name": "Crystal Palace", "lines": ["overground"]},
  {"name": "Denmark Hill", "lines": ["overground"]},
  {"name": "Deptford Bridge", "lines": ["dlr"]},
  {"name": "Edmonton Green", "lines": ["overground"]},
  {"name": "Elverson Road", "lines": ["dlr"]},
  {"name": "Enfield Town", "lines": ["overground"]},
  {"name": "Finchley Road & Frognal", "lines": ["overground"]},
  {"name": "Forest Hill", "lines": ["overground"]},
  {"name": "Gospel Oak", "lines": ["overground"]},
  {"name": "Hackney Central", "lines": ["overground"]},
  {"name": "Hackney Downs", "lines": ["overground"]},
  {"name": "Hackney Wick", "lines": ["overground"]},
  {"name": "Hampstead Heath", "lines": ["overground"]},
  {"name": "Harringay Green Lanes", "lines": ["overground"]},
  {"name": "Homerton", "lines": ["overground"]},
  {"name": "Honor Oak Park", "lines": ["overground"]},
  {"name": "Kensal Rise", "lines": ["overground"]},
  {"name": "Kentish Town West", "lines": ["overground"]},
  {"name": "Kilburn High Road", "lines": ["overground"]},
  {"name": "Leyton Midland Road", "lines": ["overground"]},
  {"name": "Leytonstone High Road", "lines": ["overground"]},
  {"name": "New Cross", "lines": ["overground"]},
  {"name": "New Cross Gate", "lines": ["overground"]},
  {"name": "Norwood Junction", "lines": ["overground"]},
  {"name": "Peckham Rye", "lines": ["overground"]},
  {"name": "Penge West", "lines": ["overground"]},
  {"name": "Queens Road Peckham", "lines": ["overground"]},
  {"name": "Rectory Road", "lines": ["overground"]},
  {"name": "Shepherd's Bush", "lines": ["overground"]},
  {"name": "Silver Street", "lines": ["overground"]},
  {"name": "South Bermondsey", "lines": ["overground"]},
  {"name": "South Hampstead", "lines": ["overground"]},
  {"name": "South Kenton", "lines": ["overground"]},
  {"name": "South Tottenham", "lines": ["overground"]},
  {"name": "Southbury", "lines": ["overground"]},
  {"name": "Stamford Hill", "lines": ["overground"]},
  {"name": "Stoke Newington", "lines": ["overground"]},
  {"name": "Sydenham", "lines": ["overground"]},
  {"name": "Theobalds Grove", "lines": ["overground"]},
  {"name": "Turkey Street", "lines": ["overground"]},
  {"name": "Walthamstow Queen's Road", "lines": ["overground"]},
  {"name": "Wandsworth Road", "lines": ["overground"]},
  {"name": "Wanstead Park", "lines": ["overground"]},
  {"name": "West Croydon", "lines": ["overground", "tram"]},
  {"name": "White Hart Lane", "lines": ["overground"]},
  {"name": "Woodgrange Park", "lines": ["overground"]},
  {"name": "Abbey Road", "lines": ["dlr"]},
  {"name": "All Saints", "lines": ["dlr"]},
  {"name": "Beckton", "lines": ["dlr"]},
  {"name": "Beckton Park", "lines": ["dlr"]},
  {"name": "Bow Church", "lines": ["dlr"]},
  {"name": "Cyprus", "lines": ["dlr"]},
  {"name": "Devons Road", "lines": ["dlr"]},
  {"name": "Gallions Reach", "lines": ["dlr"]},
  {"name": "King George V", "lines": ["dlr"]},
  {"name": "Langdon Park", "lines": ["dlr"]},
  {"name": "London City Airport", "lines": ["dlr"]},
  {"name": "Pontoon Dock", "lines": ["dlr"]},
  {"name": "Pudding Mill Lane", "lines": ["dlr"]},
  {"name": "Star Lane", "lines": ["dlr"]},
  {"name": "Stratford International", "lines": ["dlr"]},
  {"name": "West Silvertown", "lines": ["dlr"]},
  
  // Tram stops
  {"name": "Addiscombe", "lines": ["tram"]},
  {"name": "Addington Village", "lines": ["tram"]},
  {"name": "Ampere Way", "lines": ["tram"]},
  {"name": "Arena", "lines": ["tram"]},
  {"name": "Avenue Road", "lines": ["tram"]},
  {"name": "Beckenham Junction", "lines": ["tram"]},
  {"name": "Beckenham Road", "lines": ["tram"]},
  {"name": "Beddington Lane", "lines": ["tram"]},
  {"name": "Belgrave Walk", "lines": ["tram"]},
  {"name": "Birkbeck", "lines": ["tram"]},
  {"name": "Blackhorse Lane", "lines": ["tram"]},
  {"name": "Centrale", "lines": ["tram"]},
  {"name": "Church Street", "lines": ["tram"]},
  {"name": "Coombe Lane", "lines": ["tram"]},
  {"name": "Dundonald Road", "lines": ["tram"]},
  {"name": "East Croydon", "lines": ["tram"]},
  {"name": "Elmers End", "lines": ["tram"]},
  {"name": "Fieldway", "lines": ["tram"]},
  {"name": "George Street", "lines": ["tram"]},
  {"name": "Gravel Hill", "lines": ["tram"]},
  {"name": "Harrington Road", "lines": ["tram"]},
  {"name": "King Henry's Drive", "lines": ["tram"]},
  {"name": "Lebanon Road", "lines": ["tram"]},
  {"name": "Lloyd Park", "lines": ["tram"]},
  {"name": "Merton Park", "lines": ["tram"]},
  {"name": "Mitcham", "lines": ["tram"]},
  {"name": "Mitcham Junction", "lines": ["tram"]},
  {"name": "Morden Road", "lines": ["tram"]},
  {"name": "New Addington", "lines": ["tram"]},
  {"name": "Phipps Bridge", "lines": ["tram"]},
  {"name": "Reeves Corner", "lines": ["tram"]},
  {"name": "Sandilands", "lines": ["tram"]},
  {"name": "Therapia Lane", "lines": ["tram"]},
  {"name": "Waddon Marsh", "lines": ["tram"]},
  {"name": "Wandle Park", "lines": ["tram"]},
  {"name": "Wellesley Road", "lines": ["tram"]},
  {"name": "Woodside", "lines": ["tram"]},
  

  // Bus Routes
  {"name": "6", "lines": ["bus"]},
  {"name": "12", "lines": ["bus"]},
  {"name": "13", "lines": ["bus"]},
  {"name": "14", "lines": ["bus"]},
  {"name": "23", "lines": ["bus"]},
  {"name": "24", "lines": ["bus"]},
  {"name": "33", "lines": ["bus"]},
  {"name": "35", "lines": ["bus"]},
  {"name": "36", "lines": ["bus"]},
  {"name": "37", "lines": ["bus"]},
  {"name": "38", "lines": ["bus"]},
  {"name": "43", "lines": ["bus"]},
  {"name": "46", "lines": ["bus"]},
  {"name": "47", "lines": ["bus"]},
  {"name": "52", "lines": ["bus"]},
  {"name": "57", "lines": ["bus"]},
  {"name": "60", "lines": ["bus"]},
  {"name": "62", "lines": ["bus"]},
  {"name": "64", "lines": ["bus"]},
  {"name": "69", "lines": ["bus"]},
  {"name": "72", "lines": ["bus"]},
  {"name": "76", "lines": ["bus"]},
  {"name": "80", "lines": ["bus"]},
  {"name": "87", "lines": ["bus"]},
  {"name": "88", "lines": ["bus"]},
  {"name": "90", "lines": ["bus"]},
  {"name": "93", "lines": ["bus"]},
  {"name": "94", "lines": ["bus"]},
  {"name": "100", "lines": ["bus"]},
  {"name": "101", "lines": ["bus"]},
  {"name": "102", "lines": ["bus"]},
  {"name": "103", "lines": ["bus"]},
  {"name": "104", "lines": ["bus"]},
  {"name": "105", "lines": ["bus"]},
  {"name": "106", "lines": ["bus"]},
  {"name": "107", "lines": ["bus"]},
  {"name": "108", "lines": ["bus"]},
  {"name": "108D", "lines": ["bus"]},
  {"name": "111", "lines": ["bus"]},
  {"name": "115", "lines": ["bus"]},
  {"name": "116", "lines": ["bus"]},
  {"name": "119", "lines": ["bus"]},
  {"name": "123", "lines": ["bus"]},
  {"name": "124", "lines": ["bus"]},
  {"name": "125", "lines": ["bus"]},
  {"name": "126", "lines": ["bus"]},
  {"name": "128", "lines": ["bus"]},
  {"name": "130", "lines": ["bus"]},
  {"name": "134", "lines": ["bus"]},
  {"name": "138", "lines": ["bus"]},
  {"name": "139", "lines": ["bus"]},
  {"name": "140", "lines": ["bus"]},
  {"name": "143", "lines": ["bus"]},
  {"name": "144", "lines": ["bus"]},
  {"name": "145", "lines": ["bus"]},
  {"name": "147", "lines": ["bus"]},
  {"name": "148", "lines": ["bus"]},
  {"name": "149", "lines": ["bus"]},
  {"name": "150", "lines": ["bus"]},
  {"name": "151", "lines": ["bus"]},
  {"name": "155", "lines": ["bus"]},
  {"name": "158", "lines": ["bus"]},
  {"name": "159", "lines": ["bus"]},
  {"name": "161", "lines": ["bus"]},
  {"name": "163", "lines": ["bus"]},
  {"name": "164", "lines": ["bus"]},
  {"name": "165", "lines": ["bus"]},
  {"name": "166", "lines": ["bus"]},
  {"name": "169", "lines": ["bus"]},
  {"name": "170", "lines": ["bus"]},
  {"name": "171", "lines": ["bus"]},
  {"name": "172", "lines": ["bus"]},
  {"name": "173", "lines": ["bus"]},
  {"name": "174", "lines": ["bus"]},
  {"name": "175", "lines": ["bus"]},
  {"name": "176", "lines": ["bus"]},
  {"name": "177", "lines": ["bus"]},
  {"name": "178", "lines": ["bus"]},
  {"name": "179", "lines": ["bus"]},
  {"name": "182", "lines": ["bus"]},
  {"name": "184", "lines": ["bus"]},
  {"name": "186", "lines": ["bus"]},
  {"name": "187", "lines": ["bus"]},
  {"name": "188", "lines": ["bus"]},
  {"name": "189", "lines": ["bus"]},
  {"name": "190", "lines": ["bus"]},
  {"name": "192", "lines": ["bus"]},
  {"name": "194", "lines": ["bus"]},
  {"name": "195", "lines": ["bus"]},
  {"name": "197", "lines": ["bus"]},
  {"name": "198", "lines": ["bus"]},
  {"name": "200", "lines": ["bus"]},
  {"name": "202", "lines": ["bus"]},
  {"name": "203", "lines": ["bus"]},
  {"name": "204", "lines": ["bus"]},
  {"name": "206", "lines": ["bus"]},
  {"name": "208", "lines": ["bus"]},
  {"name": "209", "lines": ["bus"]},
  {"name": "211", "lines": ["bus"]},
  {"name": "213", "lines": ["bus"]},
  {"name": "214", "lines": ["bus"]},
  {"name": "217", "lines": ["bus"]},
  {"name": "218", "lines": ["bus"]},
  {"name": "219", "lines": ["bus"]},
  {"name": "220", "lines": ["bus"]},
  {"name": "222", "lines": ["bus"]},
  {"name": "223", "lines": ["bus"]},
  {"name": "224", "lines": ["bus"]},
  {"name": "228", "lines": ["bus"]},
  {"name": "229", "lines": ["bus"]},
  {"name": "230", "lines": ["bus"]},
  {"name": "233", "lines": ["bus"]},
  {"name": "234", "lines": ["bus"]},
  {"name": "235", "lines": ["bus"]},
  {"name": "236", "lines": ["bus"]},
  {"name": "237", "lines": ["bus"]},
  {"name": "238", "lines": ["bus"]},
  {"name": "241", "lines": ["bus"]},
  {"name": "243", "lines": ["bus"]},
  {"name": "244", "lines": ["bus"]},
  {"name": "245", "lines": ["bus"]},
  {"name": "246", "lines": ["bus"]},
  {"name": "248", "lines": ["bus"]},
  {"name": "249", "lines": ["bus"]},
  {"name": "251", "lines": ["bus"]},
  {"name": "254", "lines": ["bus"]},
  {"name": "255", "lines": ["bus"]},
  {"name": "256", "lines": ["bus"]},
  {"name": "259", "lines": ["bus"]},
  {"name": "263", "lines": ["bus"]},
  {"name": "264", "lines": ["bus"]},
  {"name": "265", "lines": ["bus"]},
  {"name": "266", "lines": ["bus"]},
  {"name": "267", "lines": ["bus"]},
  {"name": "268", "lines": ["bus"]},
  {"name": "270", "lines": ["bus"]},
  {"name": "272", "lines": ["bus"]},
  {"name": "273", "lines": ["bus"]},
  {"name": "274", "lines": ["bus"]},
  {"name": "275", "lines": ["bus"]},
  {"name": "278", "lines": ["bus"]},
  {"name": "279", "lines": ["bus"]},
  {"name": "281", "lines": ["bus"]},
  {"name": "282", "lines": ["bus"]},
  {"name": "284", "lines": ["bus"]},
  {"name": "285", "lines": ["bus"]},
  {"name": "286", "lines": ["bus"]},
  {"name": "287", "lines": ["bus"]},
  {"name": "288", "lines": ["bus"]},
  {"name": "289", "lines": ["bus"]},
  {"name": "290", "lines": ["bus"]},
  {"name": "291", "lines": ["bus"]},
  {"name": "292", "lines": ["bus"]},
  {"name": "294", "lines": ["bus"]},
  {"name": "295", "lines": ["bus"]},
  {"name": "296", "lines": ["bus"]},
  {"name": "297", "lines": ["bus"]},
  {"name": "298", "lines": ["bus"]},
  {"name": "299", "lines": ["bus"]},
  {"name": "300", "lines": ["bus"]},
  {"name": "301", "lines": ["bus"]},
  {"name": "303", "lines": ["bus"]},
  {"name": "304", "lines": ["bus"]},
  {"name": "306", "lines": ["bus"]},
  {"name": "307", "lines": ["bus"]},
  {"name": "308", "lines": ["bus"]},
  {"name": "309", "lines": ["bus"]},
  {"name": "310", "lines": ["bus"]},
  {"name": "313", "lines": ["bus"]},
  {"name": "317", "lines": ["bus"]},
  {"name": "319", "lines": ["bus"]},
  {"name": "321", "lines": ["bus"]},
  {"name": "325", "lines": ["bus"]},
  {"name": "326", "lines": ["bus"]},
  {"name": "327", "lines": ["bus"]},
  {"name": "328", "lines": ["bus"]},
  {"name": "329", "lines": ["bus"]},
  {"name": "330", "lines": ["bus"]},
  {"name": "331", "lines": ["bus"]},
  {"name": "335", "lines": ["bus"]},
  {"name": "340", "lines": ["bus"]},
  {"name": "341", "lines": ["bus"]},
  {"name": "344", "lines": ["bus"]},
  {"name": "345", "lines": ["bus"]},
  {"name": "346", "lines": ["bus"]},
  {"name": "349", "lines": ["bus"]},
  {"name": "350", "lines": ["bus"]},
  {"name": "353", "lines": ["bus"]},
  {"name": "354", "lines": ["bus"]},
  {"name": "355", "lines": ["bus"]},
  {"name": "356", "lines": ["bus"]},
  {"name": "357", "lines": ["bus"]},
  {"name": "359", "lines": ["bus"]},
  {"name": "364", "lines": ["bus"]},
  {"name": "365", "lines": ["bus"]},
  {"name": "366", "lines": ["bus"]},
  {"name": "368", "lines": ["bus"]},
  {"name": "370", "lines": ["bus"]},
  {"name": "371", "lines": ["bus"]},
  {"name": "372", "lines": ["bus"]},
  {"name": "375", "lines": ["bus"]},
  {"name": "376", "lines": ["bus"]},
  {"name": "377", "lines": ["bus"]},
  {"name": "378", "lines": ["bus"]},
  {"name": "379", "lines": ["bus"]},
  {"name": "380", "lines": ["bus"]},
  {"name": "381", "lines": ["bus"]},
  {"name": "382", "lines": ["bus"]},
  {"name": "383", "lines": ["bus"]},
  {"name": "384", "lines": ["bus"]},
  {"name": "385", "lines": ["bus"]},
  {"name": "389", "lines": ["bus"]},
  {"name": "390", "lines": ["bus"]},
  {"name": "393", "lines": ["bus"]},
  {"name": "395", "lines": ["bus"]},
  {"name": "396", "lines": ["bus"]},
  {"name": "397", "lines": ["bus"]},
  {"name": "398", "lines": ["bus"]},
  {"name": "401", "lines": ["bus"]},
  {"name": "403", "lines": ["bus"]},
  {"name": "404", "lines": ["bus"]},
  {"name": "405", "lines": ["bus"]},
  {"name": "406", "lines": ["bus"]},
  {"name": "407", "lines": ["bus"]},
  {"name": "410", "lines": ["bus"]},
  {"name": "412", "lines": ["bus"]},
  {"name": "413", "lines": ["bus"]},
  {"name": "417", "lines": ["bus"]},
  {"name": "418", "lines": ["bus"]},
  {"name": "419", "lines": ["bus"]},
  {"name": "423", "lines": ["bus"]},
  {"name": "424", "lines": ["bus"]},
  {"name": "425", "lines": ["bus"]},
  {"name": "428", "lines": ["bus"]},
  {"name": "430", "lines": ["bus"]},
  {"name": "432", "lines": ["bus"]},
  {"name": "433", "lines": ["bus"]},
  {"name": "434", "lines": ["bus"]},
  {"name": "439", "lines": ["bus"]},
  {"name": "440", "lines": ["bus"]},
  {"name": "450", "lines": ["bus"]},
  {"name": "453", "lines": ["bus"]},
  {"name": "460", "lines": ["bus"]},
  {"name": "462", "lines": ["bus"]},
  {"name": "464", "lines": ["bus"]},
  {"name": "466", "lines": ["bus"]},
  {"name": "467", "lines": ["bus"]},
  {"name": "468", "lines": ["bus"]},
  {"name": "469", "lines": ["bus"]},
  {"name": "473", "lines": ["bus"]},
  {"name": "474", "lines": ["bus"]},
  {"name": "481D", "lines": ["bus"]},
  {"name": "483", "lines": ["bus"]},
  {"name": "484", "lines": ["bus"]},
  {"name": "485", "lines": ["bus"]},
  {"name": "486", "lines": ["bus"]},
  {"name": "488", "lines": ["bus"]},
  {"name": "493", "lines": ["bus"]},
  {"name": "496", "lines": ["bus"]},
  {"name": "498", "lines": ["bus"]},
  {"name": "499", "lines": ["bus"]},
  {"name": "603", "lines": ["bus"]},
  {"name": "618", "lines": ["bus"]},
  {"name": "624", "lines": ["bus"]},
  {"name": "625", "lines": ["bus"]},
  {"name": "628", "lines": ["bus"]},
  {"name": "642", "lines": ["bus"]},
  {"name": "645", "lines": ["bus"]},
  {"name": "653", "lines": ["bus"]},
  {"name": "678", "lines": ["bus"]},
  {"name": "683", "lines": ["bus"]},
  {"name": "685", "lines": ["bus"]},
  {"name": "686", "lines": ["bus"]},
  {"name": "688", "lines": ["bus"]},
  {"name": "697", "lines": ["bus"]},
  {"name": "B12", "lines": ["bus"]},
  {"name": "E7", "lines": ["bus"]},
  {"name": "H2", "lines": ["bus"]},
  {"name": "H9", "lines": ["bus"]},
  {"name": "H10", "lines": ["bus"]},
  {"name": "H13", "lines": ["bus"]},
  {"name": "H14", "lines": ["bus"]},
  {"name": "H17", "lines": ["bus"]},
  {"name": "H18", "lines": ["bus"]},
  {"name": "H19", "lines": ["bus"]},
  {"name": "H20", "lines": ["bus"]},
  {"name": "H37", "lines": ["bus"]},
  {"name": "H98", "lines": ["bus"]},
  {"name": "R5", "lines": ["bus"]},
  {"name": "R10", "lines": ["bus"]},
  {"name": "R70", "lines": ["bus"]},
  {"name": "U2", "lines": ["bus"]},
  {"name": "U10", "lines": ["bus"]},
  {"name": "W12", "lines": ["bus"]},
  {"name": "W13", "lines": ["bus"]},
  {"name": "W15", "lines": ["bus"]},
  {"name": "W19", "lines": ["bus"]},
  {"name": "N9", "lines": ["bus"]},
  {"name": "N11", "lines": ["bus"]},
  {"name": "N15", "lines": ["bus"]},
  {"name": "N18", "lines": ["bus"]},
  {"name": "N20", "lines": ["bus"]},
  {"name": "N22", "lines": ["bus"]},
  {"name": "N25", "lines": ["bus"]},
  {"name": "N27", "lines": ["bus"]},
  {"name": "N28", "lines": ["bus"]},
  {"name": "N29", "lines": ["bus"]},
  {"name": "N32", "lines": ["bus"]},
  {"name": "N38", "lines": ["bus"]},
  {"name": "N41", "lines": ["bus"]},
  {"name": "N44", "lines": ["bus"]},
  {"name": "N53", "lines": ["bus"]},
  {"name": "N55", "lines": ["bus"]},
  {"name": "N72", "lines": ["bus"]},
  {"name": "N73", "lines": ["bus"]},
  {"name": "N74", "lines": ["bus"]},
  {"name": "N83", "lines": ["bus"]},
  {"name": "N86", "lines": ["bus"]},
  {"name": "N87", "lines": ["bus"]},
  {"name": "N89", "lines": ["bus"]},
  {"name": "N91", "lines": ["bus"]},
  {"name": "N97", "lines": ["bus"]},
  {"name": "N98", "lines": ["bus"]},
  {"name": "N109", "lines": ["bus"]},
  {"name": "N113", "lines": ["bus"]},
  {"name": "N118", "lines": ["bus"]},
  {"name": "N133", "lines": ["bus"]},
  {"name": "N136", "lines": ["bus"]},
  {"name": "N137", "lines": ["bus"]},
  {"name": "N140", "lines": ["bus"]},
  {"name": "N155", "lines": ["bus"]},
  {"name": "N171", "lines": ["bus"]},
  {"name": "N199", "lines": ["bus"]},
  {"name": "N205", "lines": ["bus"]},
  {"name": "N207", "lines": ["bus"]},
  {"name": "N242", "lines": ["bus"]},
  {"name": "N250", "lines": ["bus"]},
  {"name": "N253", "lines": ["bus"]},
  {"name": "N263", "lines": ["bus"]},
  {"name": "N266", "lines": ["bus"]},
  {"name": "N277", "lines": ["bus"]},
  {"name": "N279", "lines": ["bus"]},
  {"name": "N343", "lines": ["bus"]},
  {"name": "N381", "lines": ["bus"]},
  {"name": "N472", "lines": ["bus"]},
  {"name": "N550", "lines": ["bus"]},
  {"name": "N551", "lines": ["bus"]},
  {"name": "BL1", "lines": ["bus"]},
  {"name": "SL6", "lines": ["bus"]},
  {"name": "969", "lines": ["bus"]},
  {"name": "SCS", "lines": ["bus"]},

];